theme: jekyll-theme-minimal
title: <a href="https://github.com/ebsiegs">Emily Siegel</a> # your name (or website title) here
logo: "/images/1552086497412.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist | Geoscientist
  <br>
  Feel free to check out my <a href="images/Emily Siegel Resume.pdf">resume!</a>
  <br>
  <br>
  To get in touch, please reach out via <a href="https://www.linkedin.com/in/emilybsiegel/">LinkedIn</a>
  <br>
  <br>
