theme: jekyll-theme-minimal
title: <a href="https://github.com/ebsiegs">Emily Siegel</a> # your name (or website title) here
logo: "/images/1552086497412.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Data Scientist | Geoscientist
<br>
Geoscientist and Analyst turned Data Scientist with 9+ years experience achieving actionable insights through analyzing and integrating diverse datasets.
<br>
To get in touch, feel free to reach out via LinkedIn!
<br>
<a href="https://www.linkedin.com/in/emilybsiegel/">View My LinkedIn Profile</a>
<br>
<br>
theme: jekyll-theme-minimal
